module.exports = {
  apps: [
    {
      name: 'callspsy-backend',
      cwd: '/workspace/apps/backend',
      script: 'dist/src/main.js',
      interpreter: 'node',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'production',
      },
      env_file: '/workspace/.env',
      error_file: '/tmp/callspsy-backend-error.log',
      out_file:   '/tmp/callspsy-backend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      restart_delay: 3000,
      max_restarts: 10,
      min_uptime: '10s',
    },
    {
      name: 'callspsy-frontend',
      cwd: '/workspace/apps/frontend',
      script: 'node_modules/.bin/next',
      args: 'start -p 3000',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '256M',
      env: {
        NODE_ENV: 'production',
        NEXT_PUBLIC_API_URL: 'http://localhost:3001',
        NEXT_PUBLIC_WS_URL:  'http://localhost:3001',
        PORT: 3000,
      },
      error_file: '/tmp/callspsy-frontend-error.log',
      out_file:   '/tmp/callspsy-frontend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      restart_delay: 3000,
      max_restarts: 10,
      min_uptime: '10s',
    },
  ],
};
